#### Named Entity Recognition: Continuation from my notebook on Google Colab

In [1]:
import nltk

In [14]:
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...


True

In [3]:
sentence_eiffel = "The Eiffel tower was built from 1887 to 1889 by French engineer Gustave Eiffel, whose company company specialized in building metal frameworks and structures"

In [6]:
words_effiel = nltk.word_tokenize(sentence_eiffel)

In [7]:
words_effiel

['The',
 'Eiffel',
 'tower',
 'was',
 'built',
 'from',
 '1887',
 'to',
 '1889',
 'by',
 'French',
 'engineer',
 'Gustave',
 'Eiffel',
 ',',
 'whose',
 'company',
 'company',
 'specialized',
 'in',
 'building',
 'metal',
 'frameworks',
 'and',
 'structures']

In [8]:
part_of_speech_tag = nltk.pos_tag(words_effiel)

In [9]:
part_of_speech_tag

[('The', 'DT'),
 ('Eiffel', 'NNP'),
 ('tower', 'NN'),
 ('was', 'VBD'),
 ('built', 'VBN'),
 ('from', 'IN'),
 ('1887', 'CD'),
 ('to', 'TO'),
 ('1889', 'CD'),
 ('by', 'IN'),
 ('French', 'JJ'),
 ('engineer', 'NN'),
 ('Gustave', 'NNP'),
 ('Eiffel', 'NNP'),
 (',', ','),
 ('whose', 'WP$'),
 ('company', 'NN'),
 ('company', 'NN'),
 ('specialized', 'VBD'),
 ('in', 'IN'),
 ('building', 'NN'),
 ('metal', 'NN'),
 ('frameworks', 'NNS'),
 ('and', 'CC'),
 ('structures', 'NNS')]

In [11]:
nltk.download('words')
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


True

In [13]:
nltk.ne_chunk(part_of_speech_tag).draw()

#### Bags Of Words

In [1]:
import pandas as pd

In [22]:
messages = pd.read_csv("SMSSpamCollection.txt", sep = '\t', names = ["label", "messages"])

In [4]:
messages.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Data Cleaning and Preprocessing
import re
import nltk

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
lemmitizer = WordNetLemmatizer()

In [23]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['messages'][i])
    review = review.lower()
    review = review.split()
    review = [lemmitizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [24]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [29]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, binary=True)

In [30]:
X = cv.fit_transform(corpus).toarray()

In [31]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [32]:
cv.vocabulary_

{'go': np.int64(878),
 'point': np.int64(1601),
 'crazy': np.int64(471),
 'available': np.int64(145),
 'bugis': np.int64(284),
 'great': np.int64(903),
 'world': np.int64(2436),
 'la': np.int64(1144),
 'cine': np.int64(388),
 'got': np.int64(894),
 'wat': np.int64(2361),
 'ok': np.int64(1485),
 'lar': np.int64(1152),
 'joking': np.int64(1106),
 'wif': np.int64(2399),
 'oni': np.int64(1493),
 'free': np.int64(790),
 'entry': np.int64(654),
 'wkly': np.int64(2422),
 'comp': np.int64(426),
 'win': np.int64(2403),
 'cup': np.int64(484),
 'final': np.int64(741),
 'tkts': np.int64(2185),
 'st': np.int64(2015),
 'may': np.int64(1309),
 'text': np.int64(2141),
 'receive': np.int64(1716),
 'question': np.int64(1673),
 'std': np.int64(2030),
 'txt': np.int64(2256),
 'rate': np.int64(1695),
 'apply': np.int64(100),
 'dun': np.int64(613),
 'say': np.int64(1836),
 'early': np.int64(618),
 'already': np.int64(67),
 'nah': np.int64(1419),
 'think': np.int64(2158),
 'usf': np.int64(2300),
 'life': np.

#### N-Grams

In [36]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, binary=True, ngram_range=(2,2))

In [37]:
X = cv.fit_transform(corpus).toarray()

In [38]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

#### TF-IDF and N-Grams

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100)
X = tfidf.fit_transform(corpus).toarray()

In [57]:
import numpy as np

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float= lambda x: "%.3g" % x))

In [58]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [59]:
# For N-Grams
tfidf = TfidfVectorizer(max_features=100, ngram_range=(2,2))
X = tfidf.fit_transform(corpus).toarray()

In [62]:
tfidf.vocabulary_

{'free entry': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'claim code': np.int64(17),
 'free call': np.int64(32),
 'chance win': np.int64(15),
 'txt word': np.int64(89),
 'let know': np.int64(54),
 'please call': np.int64(68),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorry call': np.int64(80),
 'call later': np.int64(8),
 'ur awarded': np.int64(90),
 'hi hi': np.int64(47),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'guaranteed cash': np.int64(43),
 'cash prize': np.int64(14),
 'po box': np.int64(70),
 'trying contact': np.int64(86),
 'draw show': np.int64(29),
 'show prize': np.int64(79),
 'prize guaranteed': np.int64(74),
 'guaranteed call': np.int64(42),
 'valid hr': np.int64(95),
 'selected receive': np.int64(76),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'statement show': np.int64(82),
 'call identifier': np.int64(5),
 'identifier code':