In [2]:
import pandas as pd

In [37]:
messages = pd.read_csv("SMSSpamCollection.txt", sep = '\t', names = ["label", "messages"])

In [38]:
messages.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [39]:
# Data Cleaning and Preprocessing
import re
import nltk

In [40]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
lemmitizer = WordNetLemmatizer()

In [41]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['messages'][i])
    review = review.lower()
    review = review.split()
    review = [lemmitizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [42]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [43]:
y = pd.get_dummies(messages['label']).astype(int)
y = y.iloc[:,0].values

In [44]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size = 0.20)

In [45]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, ngram_range = (1,2))

In [46]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [47]:
import numpy as np

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float= lambda x: "%.3g" % x))

X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [48]:
cv.vocabulary_

{'yup': np.int64(2496),
 'lunch': np.int64(1233),
 'eat': np.int64(583),
 'already': np.int64(57),
 'hungry': np.int64(991),
 'gay': np.int64(765),
 'guy': np.int64(876),
 'feeling': np.int64(674),
 'call': np.int64(242),
 'min': np.int64(1298),
 'stop': np.int64(1988),
 'text': np.int64(2080),
 'call min': np.int64(255),
 'min stop': np.int64(1301),
 'stop text': np.int64(1996),
 'text call': np.int64(2082),
 'xmas': np.int64(2462),
 'prize': np.int64(1635),
 'draw': np.int64(556),
 'trying': np.int64(2191),
 'contact': np.int64(415),
 'today': np.int64(2145),
 'show': np.int64(1864),
 'guaranteed': np.int64(867),
 'land': np.int64(1091),
 'line': np.int64(1154),
 'valid': np.int64(2285),
 'hr': np.int64(984),
 'trying contact': np.int64(2192),
 'contact today': np.int64(421),
 'today draw': np.int64(2148),
 'draw show': np.int64(558),
 'show prize': np.int64(1865),
 'prize guaranteed': np.int64(1638),
 'guaranteed call': np.int64(868),
 'call land': np.int64(252),
 'land line': np.in

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [51]:
spam_detect_model

MultinomialNB()

In [52]:
y_pred = spam_detect_model.predict(X_test)

In [53]:
y_pred

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, ..., 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], shape=(1115,))

In [54]:
# Performance Evaluation
from sklearn.metrics import accuracy_score, classification_report

In [55]:
accuracy_score(y_test, y_pred)

0.9865470852017937

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.91      0.95       157
           1       0.99      1.00      0.99       958

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [58]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size = 0.20)

In [59]:
# Creating the TF-IDF Model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 2500, ngram_range = (1, 2))
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [60]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [61]:
tv.vocabulary_

{'going': np.int64(818),
 'lunch': np.int64(1233),
 'wif': np.int64(2400),
 'family': np.int64(649),
 'aft': np.int64(30),
 'dat': np.int64(475),
 'go': np.int64(801),
 'str': np.int64(2010),
 'orchard': np.int64(1513),
 'lor': np.int64(1199),
 'dont': np.int64(544),
 'give': np.int64(793),
 'wot': np.int64(2444),
 'think': np.int64(2113),
 'mind': np.int64(1312),
 'friend': np.int64(738),
 'mine': np.int64(1314),
 'sleep': np.int64(1909),
 'wiv': np.int64(2419),
 'friend mine': np.int64(740),
 'ah': np.int64(37),
 'well': np.int64(2381),
 'thing': np.int64(2112),
 'doesnt': np.int64(538),
 'thought': np.int64(2123),
 'maybe': np.int64(1279),
 'wrong': np.int64(2451),
 'already': np.int64(52),
 'sort': np.int64(1950),
 'invited': np.int64(1026),
 'tho': np.int64(2121),
 'may': np.int64(1276),
 'come': np.int64(381),
 'co': np.int64(358),
 'money': np.int64(1353),
 'omg': np.int64(1494),
 'one': np.int64(1496),
 'another': np.int64(66),
 'bad': np.int64(139),
 'day': np.int64(479),
 'en

In [62]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [63]:
# Predictions
y_pred = spam_tfidf_model.predict(X_test)

In [64]:
score = accuracy_score(y_test, y_pred)
print(score)

0.9775784753363229


In [65]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.84      0.90       140
           1       0.98      1.00      0.99       975

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

