In [2]:
import pandas as pd

In [3]:
messages = pd.read_csv("SMSSpamCollection.txt", sep = '\t', names = ["label", "messages"])

In [4]:
messages.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Data Cleaning and Preprocessing
import re
import nltk

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
lemmitizer = WordNetLemmatizer()

In [7]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['messages'][i])
    review = review.lower()
    review = review.split()
    review = [lemmitizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [9]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, ngram_range = (1,2))

In [10]:
X = cv.fit_transform(corpus).toarray()

In [11]:
import numpy as np

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float= lambda x: "%.3g" % x))

X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [12]:
cv.vocabulary_

{'go': np.int64(784),
 'point': np.int64(1624),
 'crazy': np.int64(444),
 'available': np.int64(111),
 'bugis': np.int64(221),
 'great': np.int64(843),
 'world': np.int64(2434),
 'la': np.int64(1090),
 'cine': np.int64(347),
 'got': np.int64(825),
 'wat': np.int64(2334),
 'ok': np.int64(1464),
 'lar': np.int64(1101),
 'joking': np.int64(1062),
 'wif': np.int64(2397),
 'oni': np.int64(1486),
 'ok lar': np.int64(1466),
 'free': np.int64(709),
 'entry': np.int64(608),
 'wkly': np.int64(2420),
 'comp': np.int64(397),
 'win': np.int64(2402),
 'cup': np.int64(453),
 'final': np.int64(674),
 'st': np.int64(1960),
 'may': np.int64(1260),
 'text': np.int64(2089),
 'receive': np.int64(1707),
 'question': np.int64(1673),
 'std': np.int64(1978),
 'txt': np.int64(2199),
 'rate': np.int64(1686),
 'apply': np.int64(76),
 'free entry': np.int64(714),
 'entry wkly': np.int64(610),
 'std txt': np.int64(1979),
 'txt rate': np.int64(2203),
 'rate apply': np.int64(1687),
 'dun': np.int64(566),
 'say': np.i

In [13]:
# Output Features
y = pd.get_dummies(messages['label']).astype(int)

In [14]:
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [15]:
y = y.iloc[:,0].values

In [16]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [18]:
from sklearn.naive_bayes import MultinomialNB

In [19]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [20]:
spam_detect_model

MultinomialNB()

In [21]:
y_pred = spam_detect_model.predict(X_test)

In [22]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, ..., 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], shape=(1115,))

In [24]:
# Performance Evaluation
from sklearn.metrics import accuracy_score, classification_report

In [25]:
accuracy_score(y_test, y_pred)

0.9838565022421525

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       141
           1       0.99      0.99      0.99       974

    accuracy                           0.98      1115
   macro avg       0.96      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [27]:
# Creating the TF-IDF Model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 2500, ngram_range = (1, 2))
X = tv.fit_transform(corpus).toarray()

In [28]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [29]:
tv.vocabulary_

{'go': np.int64(784),
 'point': np.int64(1624),
 'crazy': np.int64(444),
 'available': np.int64(111),
 'bugis': np.int64(221),
 'great': np.int64(843),
 'world': np.int64(2434),
 'la': np.int64(1090),
 'cine': np.int64(347),
 'got': np.int64(825),
 'wat': np.int64(2334),
 'ok': np.int64(1464),
 'lar': np.int64(1101),
 'joking': np.int64(1062),
 'wif': np.int64(2397),
 'oni': np.int64(1486),
 'ok lar': np.int64(1466),
 'free': np.int64(709),
 'entry': np.int64(608),
 'wkly': np.int64(2420),
 'comp': np.int64(397),
 'win': np.int64(2402),
 'cup': np.int64(453),
 'final': np.int64(674),
 'st': np.int64(1960),
 'may': np.int64(1260),
 'text': np.int64(2089),
 'receive': np.int64(1707),
 'question': np.int64(1673),
 'std': np.int64(1978),
 'txt': np.int64(2199),
 'rate': np.int64(1686),
 'apply': np.int64(76),
 'free entry': np.int64(714),
 'entry wkly': np.int64(610),
 'std txt': np.int64(1979),
 'txt rate': np.int64(2203),
 'rate apply': np.int64(1687),
 'dun': np.int64(566),
 'say': np.i

In [31]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [32]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [33]:
# Predictions
y_pred = spam_tfidf_model.predict(X_test)

In [34]:
score = accuracy_score(y_test, y_pred)
print(score)

0.967713004484305


In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.80      0.88       163
           1       0.97      1.00      0.98       952

    accuracy                           0.97      1115
   macro avg       0.97      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115

